version: '2'

plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      config: .eslintrc.js

checks:
  method-complexity:
    enabled: true
  method-lines:
    config:
      threshold: 150
  similar-code:
    enabled: true
  identical-code:
    enabled: true

ratings:
  paths:
    - '**.js'
    - '**.jsx'
    - '**.css'
    - '**.less'
    - '**.scss'
    - '**.sss'

exclude_paths:
  - .code/**/*
  - .github/**/*
  - .vscode/**/*
  - static/**/*
